resolver: lts-12.26
# docker:
#   enable: true
extra-deps:
  - docker-0.6.0.0
packages:
- .
image:
  containers:
    - base: fpco/ubuntu-with-libgmp:14.04
      name: "thicc-manager"
      entrypoints:
        - "manager-exe"
