resolver: lts-12.26
# docker:
#   enable: true
extra-deps:
  - grpc-etcd-client-0.1.2.0
  - grpc-api-etcd-0.2.0.0
  - proto-lens-0.4.0.1
  - proto-lens-runtime-0.4.0.2
  - http2-client-0.8.0.2
  - http2-client-grpc-0.5.0.4
  - http2-grpc-types-0.3.0.0
  - lens-labels-0.3.0.1
packages:
- .
- ../docker-hs
image:
  containers:
    - base: fpco/ubuntu-with-libgmp:14.04
      name: "thicc-manager"
      entrypoints:
        - "manager-exe"
